version: '3.3'

services:
  emoticon:
    image: amouat/dnmonster

  nginx:
    build: ./nginx
    volumes:
      - ./backend/:/backend/
      - emoticons_volume:/media
    ports:
      - 80:80

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
      - emoticons_volume:/backend/media
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env

  redis:
    image: redis:rc-alpine
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --requirepass
      - password


volumes:
    postgres_data:
    redis_data:
    emoticons_volume: